import numpy as np
import matplotlib.pyplot as plt
from python_anesthesia_simulator import Patient, Simulator

# %% Initialization patient
ts = 5
age, height, weight, sex = 74, 164, 88, 1
np.random.seed(43)
george_nominal = Patient(
    [age, height, weight, sex],
    ts=ts,
)
george_random = Patient(
    [age, height, weight, sex],
    ts=ts,
    random_PK=True,
    random_PD=True,
)

george_truncated = Patient(
    [age, height, weight, sex],
    ts=ts,
    random_PK=True,
    random_PD=True,
    truncated=1,
)

simu_uniform = Simulator(
    random_generation_arg={'distribution': 'uniform', 'patient_arg': {'ts': ts, 'random_PK': True, 'random_PD': True}}
)
simu_vitalDB = Simulator(
    random_generation_arg={'distribution': 'VitalDB', 'patient_arg': {
        'random_PK': True, 'random_PD': True, 'model_hemo': 'VitalDB', 'ts': ts}},
    disturbance_profil='VitalDB'
)

# %% run a simple simulation
N_simu = int(20 * 60/ts)

uP, uR, uN = 0.15, 0.1, 0.2

results_nominal = george_nominal.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)

results_random = george_random.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)

results_truncated = george_truncated.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)
results_uniform = simu_uniform.full_sim(
    inputs_propo=[uP]*N_simu,
    inputs_remi=[uR]*N_simu,
    inputs_nore=[uN]*N_simu,
)

results_vitalDB = simu_vitalDB.full_sim(
    inputs_propo=[uP]*N_simu,
    inputs_remi=[uR]*N_simu,
    inputs_nore=[uN]*N_simu,
)
# %% Test function


def test_different_output():
    """Ensure that the random patient have different output than the nominal"""
    assert not np.allclose(results_nominal['BIS'], results_random['BIS'])
    assert not np.allclose(results_nominal['MAP'], results_random['MAP'])
    assert not np.allclose(results_nominal['CO'], results_random['CO'])
    assert not np.allclose(results_nominal['TOL'], results_random['TOL'])

    assert not np.allclose(results_nominal['BIS'], results_truncated['BIS'])
    assert not np.allclose(results_nominal['MAP'], results_truncated['MAP'])
    assert not np.allclose(results_nominal['CO'], results_truncated['CO'])
    assert not np.allclose(results_nominal['TOL'], results_truncated['TOL'])


def test_output_range():
    """Ensure the physical feasibility of the output generated by the truncated random patient."""
    for res in [results_nominal, results_random, results_truncated, results_uniform, results_vitalDB]:
        assert np.all(res['BIS'] <= 100)
        assert np.all(res['BIS'] >= 0)
        assert np.all(res['TOL'] <= 1)
        assert np.all(res['TOL'] >= 0)
        assert np.all(res['MAP'] <= 200)
        assert np.all(res['MAP'] >= 0)
        assert np.all(res['CO'] <= 20)
        assert np.all(res['CO'] >= 0)


if __name__ == '__main__':
    for res in [results_nominal, results_random, results_truncated, results_uniform, results_vitalDB]:
        plt.subplot(3, 1, 1)
        plt.plot(res['Time']/60, res['x_nore_1'])
        plt.grid()
        plt.ylabel('BIS')
        plt.subplot(3, 1, 2)
        plt.plot(res['Time']/60, res['MAP'])
        plt.grid()
        plt.ylabel('MAP')
        plt.subplot(3, 1, 3)
        plt.plot(res['Time']/60, res['TPR'])
        plt.grid()
        plt.ylabel('TPR')
        plt.xlabel('Time (minute)')
    plt.show()

    test_different_output()
    test_output_range()

    print("All tests passed successfully.")
