import numpy as np
from python_anesthesia_simulator import patient

# %% Initialization patient
ts = 5
age, height, weight, gender = 74, 164, 88, 1
np.random.seed(42)
george_nominal = patient.Patient(
    [age, height, weight, gender],
    ts=ts,
)
george_random = patient.Patient(
    [age, height, weight, gender],
    ts=ts,
    random_PK=True,
    random_PD=True,
)

george_truncated = patient.Patient(
    [age, height, weight, gender],
    ts=ts,
    random_PK=True,
    random_PD=True,
    truncated=1,
)

# %% run a simple simulation
N_simu = int(60 * 60/ts)

uP, uR, uN = 0.15, 0.1, 2

results_nominal = george_nominal.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)

results_random = george_random.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)

results_truncated = george_truncated.full_sim(
    u_propo=[uP]*N_simu,
    u_remi=[uR]*N_simu,
    u_nore=[uN]*N_simu,
)


# %% Test function

def test_different_output():
    """Ensure that the random patient have different output than the nominal"""
    assert not np.allclose(results_nominal['BIS'], results_random['BIS'])
    assert not np.allclose(results_nominal['MAP'], results_random['MAP'])
    assert not np.allclose(results_nominal['CO'], results_random['CO'])
    assert not np.allclose(results_nominal['TOL'], results_random['TOL'])

    assert not np.allclose(results_nominal['BIS'], results_truncated['BIS'])
    assert not np.allclose(results_nominal['MAP'], results_truncated['MAP'])
    assert not np.allclose(results_nominal['CO'], results_truncated['CO'])
    assert not np.allclose(results_nominal['TOL'], results_truncated['TOL'])


def test_acceptable_random_output():
    """Ensure the physical feasibility of the output generated by the random patient."""
    assert np.all(results_random['BIS'] <= 100)
    assert np.all(results_random['BIS'] >= 0)
    assert np.all(results_random['TOL'] <= 1)
    assert np.all(results_random['TOL'] >= 0)
    assert np.all(results_random['MAP'] <= 200)
    assert np.all(results_random['MAP'] >= 0)
    assert np.all(results_random['CO'] <= 20)
    assert np.all(results_random['CO'] >= 0)


def test_truncated_random_output():
    """Ensure the physical feasibility of the output generated by the truncated random patient."""
    assert np.all(results_truncated['BIS'] <= 100)
    assert np.all(results_truncated['BIS'] >= 0)
    assert np.all(results_truncated['TOL'] <= 1)
    assert np.all(results_truncated['TOL'] >= 0)
    assert np.all(results_truncated['MAP'] <= 200)
    assert np.all(results_truncated['MAP'] >= 0)
    assert np.all(results_truncated['CO'] <= 20)
    assert np.all(results_truncated['CO'] >= 0)


if __name__ == '__main__':
    test_different_output()
    test_acceptable_random_output()
    test_truncated_random_output()

    print("All tests passed successfully.")
